sudo: required

language: java
jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "api-testing-training-01"
    token: ${SONAR_TOKEN}

script:
  - ./gradlew test
  - sonar-scanner
  - ./gradlew check

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: true
